name: Deploy to AWS ECS

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Sync files to S3
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://my-deployment-artifact/ --region $AWS_REGION

      # Step 3: Create CodeDeploy Deployment
      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name my-codedeploy-app \
            --deployment-group-name my-deployment-group \
            --s3-location bucket=my-deployment-artifact,bundleType=zip,key=appspec.yml \
            --region $AWS_REGION
